stages:

- stage: ProvisionEnvironment
  variables:
    - group: 'Terraform'
    - name: tfstate-name
      value: 'bootstrapped.tfstate'
    - name: location
      value: 'westeurope'

  jobs:
  - job: TransformConfiguration
    pool:      
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: envsubst < terraform.tfvars > main.tmp && mv main.tmp terraform.tfvars && cat terraform.tfvars && printenv
      displayName: 'Replace tokens in tfvars'
      workingDirectory: ./env
      env:
        subscriptionid: $(subscriptionid)
        clientid: $(clientid)
        clientsecret: $(clientsecret)
        tenantid: $(tenantid)
        location: $(location)
        
    - script: |
        terraform init \
          -backend-config="resource_group_name=$(resourcegroup)" \
          -backend-config="storage_account_name=$(storageaccount)" \
          -backend-config="container_name=$(containername)" \
          -backend-config="key=$(tfstatename)" \
          -backend-config="access_key=$(accesskey)"

      workingDirectory: ./env
      displayName: 'Terraform init'

    - script: terraform apply -auto-approve
      workingDirectory: ./env
      displayName: 'Terraform apply'